### ISSUE TITLE
.m2拒绝访问

### ISSUE THREAD

**Issue by shyheng** [SmartIDE/SmartIDE#19]
v0.1.9.1753
2022-01-03 15:51:35.654 INFO  正在获取模板 ...
2022-01-03 15:51:36.446 INFO  SmartIDE启动中 ...
2022-01-03 15:51:36.446 INFO  读取工作区信息 ...
2022-01-03 15:51:37.802 INFO  新增工作区！
2022-01-03 15:51:38.120 INFO  创建临时目录(.temp)，请在 Git 中忽略此目录：C:\Test\idea\.ide\.temp
2022-01-03 15:51:38.140 INFO  [SSH] 转发端口：6822
Creating smartide-java-template ... error

ERROR: for smartide-java-template  Cannot create container for service smartide-java-template: mkdir C:\Program Files\Git\bin\.m2: Access is denied.

ERROR: for smartide-java-template  Cannot create container for service smartide-java-template: mkdir C:\Program Files\Git\bin\.m2: Access is denied.
ERROR: Encountered errors while bringing up the project.
2022-01-03 15:51:41.635 FATAL ; exit status 1; goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/leansoftX/smartide-cli/pkg/common.(*smartIDELogStruct).Fatal(0x25af031, {0x24e8aa0, 0xc00067e000}, {0x0, 0x0, 0x0})
        /home/localadmin/agents/agent01/_work/1/s/pkg/common/log.go:86 +0x1e5
github.com/leansoftX/smartide-cli/cmd/start.ExecuteStartCmd({0x0, {0x0, 0x0}, {0xc0000dc460, 0xc}, {0x25ae357, 0xe}, {0xc0000aeba0, 0x30}, {0x25a3dcb, ...}, ...}, ...)
        /home/localadmin/agents/agent01/_work/1/s/cmd/start/local.go:128 +0xbcc
github.com/leansoftX/smartide-cli/cmd.glob..func6(0x36903c0, {0xc000021a70, 0x1, 0x3})
        /home/localadmin/agents/agent01/_work/1/s/cmd/new.go:138 +0xa88
github.com/spf13/cobra.(*Command).execute(0x36903c0, {0xc000021a40, 0x3, 0x3})
        /home/localadmin/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x368fec0)
        /home/localadmin/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/localadmin/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/leansoftX/smartide-cli/cmd.Execute({{0xc000034470, 0xb}, {0xc000034440, 0xa}, {0xc00034de60, 0x21}, {0xc00034de90, 0x28}, {0xc00034deb0, 0x8}, ...})
        /home/localadmin/agents/agent01/_work/1/s/cmd/root.go:75 +0x79
main.main()
        /home/localadmin/agents/agent01/_work/1/s/main.go:44 +0x118

**Comment by chileeb** [comment]
根据这个信息：mkdir C:\Program Files\Git\bin.m2: Access is denied.来看，是目录权限问题。
可以调整.ide/.ide.yaml中的.m2路径尝试一下。
